### PR TITLE
Refreshed the Readme so that it reflects changes of PR #22

### PR DESCRIPTION
**Pull request by leonex-cstoller**
Sorry, again. My last commit for #22 came too late. You have already merged it @mg.
I have refreshed the `README.md` so that it reflects the current behaviour and used 'placeholder' as identifier for the clone in the affix directive. So that it becomes mor clear what the clone is used for ;-)

This commit does not change any functionality.

### CODE REVIEW

**Comment by mg** [comment]
np, thanks for the effort

**Comment by leonex-cstoller** [comment]
Excuse me @mg did you forget to merge this PR or is there any reason why you don't like to merge it? If I could do anything, please let me know ;-)

**Comment by leonex-cstoller** [comment]
hi again. Excuse me, but it would be really nice if you could merge this PR. Because currently I have to reference my fork in one of our projects, which is not very clean

**Comment by naitsirch** [comment]
Great! Thank you! :+1:

**Pull request merged**
